//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook:IBookstoreService
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        BookStoreEntities _db = new BookStoreEntities();
        public void insertbook(string title, string author, decimal price, string image)
        {
            tblBook _obj = new tblBook();
            _obj.Title = title;
            _obj.Author = author;
            _obj.Price = price;
            _obj.Image = image;
            _db.tblBooks.Add(_obj);
            _db.SaveChanges();
        }
    }
}
