//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblCustomer
    {
        public int Id { get; set; }
        [Required(ErrorMessage = " name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email is required")]
        public string Email_Id { get; set; }
        [Required(ErrorMessage = "Phone No is required")]
        
        public string PhoneNo { get; set; }
        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }
        public string PurchaseBooks { get; set; }
        BookStoreEntities _db = new BookStoreEntities();
        public void InsertCustomerRecord(string name,string email,string phoneno,string addres,string purchase)
        {
            tblCustomer _obj = new tblCustomer();
            _obj.Name = name;
            _obj.Email_Id = email;
            _obj.PhoneNo = phoneno;
            _obj.Address = addres;
            _obj.PurchaseBooks = purchase;
            _db.tblCustomers.Add(_obj);
            _db.SaveChanges();

        }
    }
}
